/* This file is generated by tdr. */
/* No manual modification is permitted. */

/* metalib version: 1 */
/* metalib md5sum: 32031a21eca7d272defb047611f84359 */

/* creation time: Wed Jul 16 17:37:33 2014 */
/* tdr version: 2.6.7, build at 20131230 */


using System;
using System.Diagnostics;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using System.Text;
using tsf4g_tdr_csharp;

namespace wl_res
{


public class ItemTriggerInfo : tsf4g_csharp_interface
{
    /* public members */
    public UInt32 ItemID;
    public UInt32 ItemType;
    public float[] DataParam;
    public UInt32 ItemTriggerEvent;
    public UInt32 TriggerData;
    public byte TriggerOnce;

    /* construct methods */
    public ItemTriggerInfo()
    {
        DataParam = new float[3];
    }

    /* public methods */
    public TdrError.ErrorType construct()
    {
        TdrError.ErrorType ret = TdrError.ErrorType.TDR_NO_ERROR;

        /*no need to  set defaultvalue */

        return ret;
    }

    public TdrError.ErrorType pack(ref byte[] buffer, int size,ref int usedSize , uint cutVer)
    {
        if (null == buffer || 0 == buffer.GetLength(0) || (size > buffer.GetLength(0)))
        {
            return TdrError.ErrorType.TDR_ERR_INVALID_BUFFER_PARAMETER;
        }

        TdrWriteBuf destBuf = new TdrWriteBuf(ref buffer, size);
        TdrError.ErrorType ret = pack(ref destBuf, cutVer);
        if (ret == TdrError.ErrorType.TDR_NO_ERROR)
        {
            buffer = destBuf.getBeginPtr();

            usedSize = destBuf.getUsedSize();
        }

        return ret;
    }

    public TdrError.ErrorType pack(ref TdrWriteBuf destBuf,  uint cutVer)
    {
        TdrError.ErrorType ret = TdrError.ErrorType.TDR_NO_ERROR;

        /* adjust cutversion */
        if (0 == cutVer || ItemTriggerInfo.CURRVERSION < cutVer)
        {
            cutVer = ItemTriggerInfo.CURRVERSION;
        }

        /* check cutversion */
        if (ItemTriggerInfo.BASEVERSION > cutVer)
        {
            return TdrError.ErrorType.TDR_ERR_CUTVER_TOO_SMALL;
        }

        /* pack member: this.ItemID */
        {
            ret = destBuf.writeUInt32(this.ItemID);
            if (TdrError.ErrorType.TDR_NO_ERROR != ret)
            {
                return ret;
            }
        }

        /* pack member: this.ItemType */
        {
            ret = destBuf.writeUInt32(this.ItemType);
            if (TdrError.ErrorType.TDR_NO_ERROR != ret)
            {
                return ret;
            }
        }

        /* pack member: this.DataParam */
        {
            for (Int32 DataParam_i = 0; DataParam_i < 3; DataParam_i++)
            {
                ret = destBuf.writeFloat(this.DataParam[DataParam_i]);
                if (TdrError.ErrorType.TDR_NO_ERROR != ret)
                {
                    return ret;
                }
            }
        }

        /* pack member: this.ItemTriggerEvent */
        {
            ret = destBuf.writeUInt32(this.ItemTriggerEvent);
            if (TdrError.ErrorType.TDR_NO_ERROR != ret)
            {
                return ret;
            }
        }

        /* pack member: this.TriggerData */
        {
            ret = destBuf.writeUInt32(this.TriggerData);
            if (TdrError.ErrorType.TDR_NO_ERROR != ret)
            {
                return ret;
            }
        }

        /* pack member: this.TriggerOnce */
        {
            ret = destBuf.writeUInt8(this.TriggerOnce);
            if (TdrError.ErrorType.TDR_NO_ERROR != ret)
            {
                return ret;
            }
        }

        return ret;
    }

    public TdrError.ErrorType unpack(ref byte [] buffer, int size, ref int usedSize , uint cutVer)
    {
        if (null == buffer || 0 == buffer.GetLength(0) || size > buffer.GetLength(0))
        {
            return TdrError.ErrorType.TDR_ERR_INVALID_BUFFER_PARAMETER;
        }

        TdrReadBuf srcBuf = new TdrReadBuf(ref buffer, size);
        TdrError.ErrorType ret = unpack(ref srcBuf, cutVer);

        usedSize = srcBuf.getUsedSize();

        return ret;
    }

    public TdrError.ErrorType unpack(ref TdrReadBuf srcBuf, uint cutVer)
    {
        TdrError.ErrorType ret = TdrError.ErrorType.TDR_NO_ERROR;

        /* adjust cutversion */
        if (0 == cutVer || ItemTriggerInfo.CURRVERSION < cutVer)
        {
            cutVer = ItemTriggerInfo.CURRVERSION;
        }

        /* check cutversion */
        if (ItemTriggerInfo.BASEVERSION > cutVer)
        {
            return TdrError.ErrorType.TDR_ERR_CUTVER_TOO_SMALL;
        }

        /* unpack member: this.ItemID */
        {
            ret = srcBuf.readUInt32(ref this.ItemID);
            if (TdrError.ErrorType.TDR_NO_ERROR != ret)
            {
                return ret;
            }
        }

        /* unpack member: this.ItemType */
        {
            ret = srcBuf.readUInt32(ref this.ItemType);
            if (TdrError.ErrorType.TDR_NO_ERROR != ret)
            {
                return ret;
            }
        }

        /* unpack member: this.DataParam */
        {
            for (Int32 DataParam_i = 0; DataParam_i < 3; DataParam_i++)
            {
                ret = srcBuf.readFloat(ref this.DataParam[DataParam_i]);
                if (TdrError.ErrorType.TDR_NO_ERROR != ret)
                {
                    return ret;
                }
            }
        }

        /* unpack member: this.ItemTriggerEvent */
        {
            ret = srcBuf.readUInt32(ref this.ItemTriggerEvent);
            if (TdrError.ErrorType.TDR_NO_ERROR != ret)
            {
                return ret;
            }
        }

        /* unpack member: this.TriggerData */
        {
            ret = srcBuf.readUInt32(ref this.TriggerData);
            if (TdrError.ErrorType.TDR_NO_ERROR != ret)
            {
                return ret;
            }
        }

        /* unpack member: this.TriggerOnce */
        {
            ret = srcBuf.readUInt8(ref this.TriggerOnce);
            if (TdrError.ErrorType.TDR_NO_ERROR != ret)
            {
                return ret;
            }
        }

        return ret;
    }

    public TdrError.ErrorType load(ref byte [] buffer, int size, ref int usedSize , uint cutVer)
    {
        if (null == buffer || 0 == buffer.GetLength(0) || size > buffer.GetLength(0))
        {
            return TdrError.ErrorType.TDR_ERR_INVALID_BUFFER_PARAMETER;
        }

        TdrReadBuf srcBuf = new TdrReadBuf(ref buffer, size);
        TdrError.ErrorType ret = load(ref srcBuf, cutVer);

        usedSize = srcBuf.getUsedSize();

        return ret;
    }

    public TdrError.ErrorType load(ref TdrReadBuf srcBuf, uint cutVer)
    {
        srcBuf.disableEndian();
        TdrError.ErrorType ret = TdrError.ErrorType.TDR_NO_ERROR;

        /* adjust cutversion */
        if (0 == cutVer || ItemTriggerInfo.CURRVERSION < cutVer)
        {
            cutVer = ItemTriggerInfo.CURRVERSION;
        }

        /* check cutversion */
        if (ItemTriggerInfo.BASEVERSION > cutVer)
        {
            return TdrError.ErrorType.TDR_ERR_CUTVER_TOO_SMALL;
        }

        /* load member: this.ItemID */
        {
            ret = srcBuf.readUInt32(ref this.ItemID);
            if (TdrError.ErrorType.TDR_NO_ERROR != ret)
            {
                return ret;
            }
        }

        /* load member: this.ItemType */
        {
            ret = srcBuf.readUInt32(ref this.ItemType);
            if (TdrError.ErrorType.TDR_NO_ERROR != ret)
            {
                return ret;
            }
        }

        /* load member: this.DataParam */
        {
            for (Int32 DataParam_i = 0; DataParam_i < 3; DataParam_i++)
            {
                ret = srcBuf.readFloat(ref this.DataParam[DataParam_i]);
                if (TdrError.ErrorType.TDR_NO_ERROR != ret)
                {
                    return ret;
                }
            }
        }

        /* load member: this.ItemTriggerEvent */
        {
            ret = srcBuf.readUInt32(ref this.ItemTriggerEvent);
            if (TdrError.ErrorType.TDR_NO_ERROR != ret)
            {
                return ret;
            }
        }

        /* load member: this.TriggerData */
        {
            ret = srcBuf.readUInt32(ref this.TriggerData);
            if (TdrError.ErrorType.TDR_NO_ERROR != ret)
            {
                return ret;
            }
        }

        /* load member: this.TriggerOnce */
        {
            ret = srcBuf.readUInt8(ref this.TriggerOnce);
            if (TdrError.ErrorType.TDR_NO_ERROR != ret)
            {
                return ret;
            }
        }

        return ret;
    }

    /* set indent = -1 to disable indent , default: separator = '\n' */
    public TdrError.ErrorType visualize(ref string buffer,int indent , char separator)
    {
        TdrVisualBuf destBuf = new TdrVisualBuf();
        TdrError.ErrorType ret = visualize(ref destBuf, indent, separator);

        buffer = destBuf.getVisualBuf();

        return ret;
    }

    /* set indent = -1 to disable indent , default: separator = '\n' */
    public TdrError.ErrorType visualize(ref TdrVisualBuf destBuf, int indent, char separator)
    {
        TdrError.ErrorType ret = TdrError.ErrorType.TDR_NO_ERROR;

        /* visualize member: this.ItemID */
        ret = TdrBufUtil.printVariable(ref destBuf, indent, separator, "[ItemID]", "{0:d}", this.ItemID);
        if (TdrError.ErrorType.TDR_NO_ERROR != ret)
        {
            return ret;
        }

        /* visualize member: this.ItemType */
        ret = TdrBufUtil.printVariable(ref destBuf, indent, separator, "[ItemType]", "{0:d}", this.ItemType);
        if (TdrError.ErrorType.TDR_NO_ERROR != ret)
        {
            return ret;
        }

        /* visualize member: this.DataParam */
        ret = TdrBufUtil.printArray(ref destBuf, indent, separator, "[DataParam]", 3);
        if (TdrError.ErrorType.TDR_NO_ERROR != ret)
        {
            return ret;
        }
        for (Int32 DataParam_i = 0; DataParam_i < 3; DataParam_i++)
        {
            ret = destBuf.sprintf("{0:g}", this.DataParam[DataParam_i]);
            if (TdrError.ErrorType.TDR_NO_ERROR != ret)
            {
                return ret;
            }
        }

        ret = destBuf.sprintf("{0}",separator);
        if (TdrError.ErrorType.TDR_NO_ERROR != ret)
        {
            return ret;
        }

        /* visualize member: this.ItemTriggerEvent */
        ret = TdrBufUtil.printVariable(ref destBuf, indent, separator, "[ItemTriggerEvent]", "{0:d}", this.ItemTriggerEvent);
        if (TdrError.ErrorType.TDR_NO_ERROR != ret)
        {
            return ret;
        }

        /* visualize member: this.TriggerData */
        ret = TdrBufUtil.printVariable(ref destBuf, indent, separator, "[TriggerData]", "{0:d}", this.TriggerData);
        if (TdrError.ErrorType.TDR_NO_ERROR != ret)
        {
            return ret;
        }

        /* visualize member: this.TriggerOnce */
        ret = TdrBufUtil.printVariable(ref destBuf, indent, separator, "[TriggerOnce]", "0x{0:x2}", this.TriggerOnce);
        if (TdrError.ErrorType.TDR_NO_ERROR != ret)
        {
            return ret;
        }

        return ret;
    }

    public TdrError.ErrorType getSizeInfo(byte[] buffer ,int size , ref uint sizeInfo)
    {
        if (0 == buffer.GetLength(0) || size > buffer.GetLength(0))
        {
            return TdrError.ErrorType.TDR_ERR_INVALID_BUFFER_PARAMETER;
        }

        TdrReadBuf srcBuf = new TdrReadBuf(ref buffer, size);
        TdrError.ErrorType ret = getSizeInfo(srcBuf, ref sizeInfo);

        return ret;
    }

    public TdrError.ErrorType getSizeInfo(TdrReadBuf srcBuf, ref uint sizeInfo)
    {
        return TdrError.ErrorType.TDR_ERR_HAVE_NOT_SET_SIZEINFO;
    }

    /*  pstMeta version info */
    public static readonly uint BASEVERSION = 1;
    public static readonly uint CURRVERSION = 1;
    /*  entry version info */
}


}
